[package]
name = "meme_generator_xixi"
description = "Extra memes for meme-generator-rs: xixi_holdsign_1 / xixi_holdsign_2 / kurogames_iuno_say"
version = "0.1.0"
authors = ["xixi <xixi@example.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/xixi/meme-generator-xixi"
repository = "https://github.com/xixi/meme-generator-xixi"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
inventory = "0.3"
serde = "1.0"
skia-safe = { version = "0.93", features = ["textlayout"] }

meme_generator_core = "0.0.5"
meme_generator_utils = "0.0.9"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
