[package]
name = "meme_generator_xixi"
description = "Extra memes for meme-generator-rs: xixi_holdsign_1-6 / yaya_holdsign_1-6 / ams_holdsign_1-6 / xixi_goldpig / xixi_goldpig_2 / kurogames_iuno_say / zhaoren_nongni"
version = "0.1.0"
authors = ["xixi <xixi@example.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/xixi/meme-generator-xixi"
repository = "https://github.com/xixi/meme-generator-xixi"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
inventory = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
skia-safe = { version = "0.93", features = ["textlayout"] }

meme_generator_core = "0.0.5"
meme_generator_utils = "0.0.9"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
